import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/NavBar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.Sample"]);
    console.log(hello.data)
    return (
        <>
            <Head>
                <title>Aaron's Checklist</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <h1 className='pt-2 w-[700px] justify-center items-center mx-auto text-center text-2xl	'>
                Api Stuff
            </h1>
            <p>{JSON.stringify(hello.data)}</p>
        </>
    );
};

export default Home;
