import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/NavBar";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Aaron's Checklist</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>
                Login
            </h1>
            <p>Email</p>
            <input/>
            <p>Password</p>
            <input/>
            <button >Login</button>
            <button >Register</button>
        </>
    );
};

export default Home;
