import type { NextPage } from "next";
import Head from "next/head";
import { InputText } from 'primereact/inputtext';
import { Button } from 'primereact/button';
import { useState } from "react";

// const Home: NextPage = () => {

//     // const handleLogin = () => {
        
//     // }

//     return (
//         <>
//             <Head>
//                 <title>Aaron's Checklist</title>
//                 <meta name="description" content="Generated by create-t3-app" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <h1>
//                 Login
//             </h1>
//             <span className="p-float-label">
//             <InputText/>
//             <label htmlFor="in">Email</label>
//             </span>
//             <span className="p-float-label">
//             <InputText/>
//             <label htmlFor="in">Password</label>
//             </span>
//             <Button >Submit</Button>
//             <Button className='ml-2'>Login</Button>
//         </>
//     );
// };

// export default Home;
